In [1]:
import torch

## 인덱싱

In [2]:
x = torch.Tensor([[1, 2], [3, 4]])
print(x[:, 1])

tensor([2., 4.])


## View

In [3]:
x = torch.randn(4, 5)
y = x.view(20)
z = x.view(5, -1)

print(x)
print(y)
print(z)

tensor([[ 0.3114, -1.5576,  0.6089, -0.5731, -0.7946],
        [ 0.2505, -0.2137,  1.8551, -0.6330, -1.4387],
        [-0.6269, -1.3936, -0.2002, -0.7241,  0.1833],
        [ 0.7976, -0.0186, -0.4982,  0.8449,  1.3129]])
tensor([ 0.3114, -1.5576,  0.6089, -0.5731, -0.7946,  0.2505, -0.2137,  1.8551,
        -0.6330, -1.4387, -0.6269, -1.3936, -0.2002, -0.7241,  0.1833,  0.7976,
        -0.0186, -0.4982,  0.8449,  1.3129])
tensor([[ 0.3114, -1.5576,  0.6089, -0.5731],
        [-0.7946,  0.2505, -0.2137,  1.8551],
        [-0.6330, -1.4387, -0.6269, -1.3936],
        [-0.2002, -0.7241,  0.1833,  0.7976],
        [-0.0186, -0.4982,  0.8449,  1.3129]])


## Item

In [5]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.4627])
0.46272435784339905
torch.float32


스칼라값 하나만 존재해야 함

In [ ]:
# error

x = torch.randn(2)
print(x)
print(x.item())
print(x.dtype)

## Squeeze

In [10]:
t = torch.rand(1, 3, 3)
print(t)
print(t.shape)

tensor([[[0.2977, 0.1754, 0.8905],
         [0.6087, 0.0433, 0.4545],
         [0.5659, 0.8955, 0.4652]]])
torch.Size([1, 3, 3])


In [11]:
s = t.squeeze()

print(s)
print(s.shape)

tensor([[0.2977, 0.1754, 0.8905],
        [0.6087, 0.0433, 0.4545],
        [0.5659, 0.8955, 0.4652]])
torch.Size([3, 3])


## Unsqueeze

In [12]:
t = torch.rand(1, 3, 3)
print(t)
print(t.shape)

tensor([[[0.2377, 0.8652, 0.6930],
         [0.9596, 0.3690, 0.4586],
         [0.5606, 0.6320, 0.9142]]])
torch.Size([1, 3, 3])


In [13]:
s = t.unsqueeze(dim=0)

print(s)
print(s.shape)

tensor([[[[0.2377, 0.8652, 0.6930],
          [0.9596, 0.3690, 0.4586],
          [0.5606, 0.6320, 0.9142]]]])
torch.Size([1, 1, 3, 3])


## Stack

In [14]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Cat

In [16]:
a = torch.randn(1, 1, 3, 3)
b = torch.randn(1, 1, 3, 3)
c = torch.cat((a, b), dim = 0)

print(c)
print(c.shape)

tensor([[[[ 1.2793, -1.8122, -0.4603],
          [-0.4636, -0.8963, -0.4037],
          [-0.3624, -0.2423, -1.9395]]],


        [[[-0.2525,  1.5356, -1.2392],
          [-0.7102,  0.0603,  1.3236],
          [ 0.9666,  0.0430,  1.1598]]]])
torch.Size([2, 1, 3, 3])


In [17]:
a = torch.randn(1, 1, 3, 3)
b = torch.randn(1, 1, 3, 3)
c = torch.cat((a, b), dim = 2)

print(c)
print(c.shape)

tensor([[[[ 0.3444, -0.3992, -1.0822],
          [ 0.0614,  0.1266,  0.9905],
          [-1.8172,  0.4659,  0.8966],
          [ 1.2097,  0.1043, -0.6026],
          [ 0.5170,  1.4154, -0.1849],
          [ 0.5803,  0.0898,  1.5115]]]])
torch.Size([1, 1, 6, 3])


## Chunk

In [18]:
t = torch.randn(3, 6)
t1, t2, t3 = torch.chunk(t, 3, dim=1)

print(t)
print(t1)
print(t2)
print(t3)

tensor([[-1.2473, -0.0945,  1.6750, -0.3555, -0.1611, -0.4919],
        [ 0.6145,  0.9226,  0.6055, -0.7205, -0.3153,  0.0157],
        [-0.7528, -0.2231, -0.3155, -0.4121, -0.1183, -0.3288]])
tensor([[-1.2473, -0.0945],
        [ 0.6145,  0.9226],
        [-0.7528, -0.2231]])
tensor([[ 1.6750, -0.3555],
        [ 0.6055, -0.7205],
        [-0.3155, -0.4121]])
tensor([[-0.1611, -0.4919],
        [-0.3153,  0.0157],
        [-0.1183, -0.3288]])


## Split

In [21]:
 t = torch.rand(3, 6)
 t1, t2 = torch.split(t, 3, dim=1)

 print(t)
 print(t1)
 print(t2)

tensor([[0.3450, 0.3517, 0.9458, 0.6299, 0.9866, 0.7382],
        [0.5873, 0.3938, 0.8956, 0.7538, 0.2059, 0.3986],
        [0.4444, 0.0157, 0.2567, 0.4892, 0.0654, 0.3537]])
tensor([[0.3450, 0.3517, 0.9458],
        [0.5873, 0.3938, 0.8956],
        [0.4444, 0.0157, 0.2567]])
tensor([[0.6299, 0.9866, 0.7382],
        [0.7538, 0.2059, 0.3986],
        [0.4892, 0.0654, 0.3537]])
