In [1]:
import torch

#  자동 미분 흐름 다시보기1

In [2]:
a = torch.ones(2, 2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [3]:
 a = torch.ones(2, 2, requires_grad=True)
 print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [10]:
print("a.data:", a)
print("a.grad_fn", a.grad_fn)

a.data: tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
a.grad_fn None


In [11]:
b = a + 2
print(b)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [12]:
c = b ** 2
print(c)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)


In [13]:
out = c.sum()
print(out)

tensor(36., grad_fn=<SumBackward0>)


In [14]:
print(out)
out.backward()

tensor(36., grad_fn=<SumBackward0>)


### 출력해보면서 확인

In [18]:
print("a.data:", a)
print("a.grad: ", a.grad)
print("a.grad_fn", a.grad_fn)

a.data: tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
a.grad:  tensor([[6., 6.],
        [6., 6.]])
a.grad_fn None


In [19]:
print("b.data:", b)
print("b.grad: ", b.grad)
print("b.grad_fn", b.grad_fn)

b.data: tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
b.grad:  None
b.grad_fn <AddBackward0 object at 0x7f5d7b3580d0>


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  


In [20]:
print("c.data:", c)
print("c.grad: ", c.grad)
print("c.grad_fn", c.grad_fn)

c.data: tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)
c.grad:  None
c.grad_fn <PowBackward0 object at 0x7f5d7b3c3410>


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  


In [21]:
print("out.data:", out)
print("out.grad: ", out.grad)
print("out.grad_fn", out.grad_fn)

out.data: tensor(36., grad_fn=<SumBackward0>)
out.grad:  None
out.grad_fn <SumBackward0 object at 0x7f5d7b366150>


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  


# 자동 미분 흐름 다시보기2

In [23]:
x = torch.ones(3, requires_grad=True)
y = (x ** 2)
z = y ** 2 + x
out = z.sum()
print(out)

tensor(6., grad_fn=<SumBackward0>)


In [24]:
grad = torch.Tensor([0.1, 1, 100])
z.backward(grad)

In [25]:
print("x.data:", x)
print("x.grad: ", x.grad)
print("x.grad_fn", x.grad_fn)

x.data: tensor([1., 1., 1.], requires_grad=True)
x.grad:  tensor([  0.5000,   5.0000, 500.0000])
x.grad_fn None


In [26]:
print("y.data:", y)
print("y.grad: ", y.grad)
print("y.grad_fn", y.grad_fn)

y.data: tensor([1., 1., 1.], grad_fn=<PowBackward0>)
y.grad:  None
y.grad_fn <PowBackward0 object at 0x7f5d7b34df10>


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  


In [27]:
print("z.data:", z)
print("z.grad: ", z.grad)
print("z.grad_fn", z.grad_fn)

z.data: tensor([2., 2., 2.], grad_fn=<AddBackward0>)
z.grad:  None
z.grad_fn <AddBackward0 object at 0x7f5d79402a10>


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  
